---
title: "test"
output: html_document
date: "2024-12-18"
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pregunta 1:

**1.** Dado un registro de vehículos que circulan por una autopista,
disponemos de su marca y modelo, país de matriculación, y tipo de
vehículo (por número de ruedas). Con tal de ajustar precios de los
peajes, ¿Cuántos vehículos tenemos por tipo? ¿Cuál es el tipo más
frecuente? ¿De qué países tenemos más vehículos?

*Es un ejemplo de datos descriptivo, ya simplemente indican los tipos de
datos que circulan por la autopista.*

**2.** Dado un registro de visualizaciones de un servicio de
video-on-demand, donde disponemos de los datos del usuario, de la
película seleccionada, fecha de visualización y categoría de la
película, queremos saber ¿Hay alguna preferencia en cuanto a género
literario según los usuarios y su rango de edad?

*Es un tipo de datos exploratorio, ya que busca relacionar el tipo de
usuario con generos literarios.*

**3.** Dado un registro de peticiones a un sitio web, vemos que las
peticiones que provienen de una red de telefonía concreta acostumbran a
ser incorrectas y provocarnos errores de servicio. ¿Podemos determinar
si en el futuro, los próximos mensajes de esa red seguirán dando
problemas? ¿Hemos notado el mismo efecto en otras redes de telefonía?

*Es un ejemplo predictivo al tratar de ver qué puede pasar en el futuro
con este mismo operador*

**4.** Dado los registros de usuarios de un servicio de compras por
internet, los usuarios pueden agruparse por preferencias de productos
comprados. Queremos saber si ¿Es posible que, dado un usuario al azar y
según su historial, pueda ser directamente asignado a un o diversos
grupos?

*En este caso son datos inferenciales ya que a partir de unos datos
iniciales de una serie de usuarios se trata de generalizar el
comportamiento al resto de los usuarios.*
